
name: Exécution des Tests


on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.12, 3.11, 3.10]
    steps:

      - name: Checkout du code source
        uses: actions/checkout@v3
      

      - name: Configuration de Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      
     
      - name: Installation des dépendances
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      

      - name: Exécution des tests
        run: pytest
